### ISSUE TITLE
Working Pipeline

### ISSUE THREAD

**Issue by StepTurtle** [davutcanakbas/dynamic_object_removal#1]
Hey,
Thanks for work. I have some questions?

When I run lidar_centerpoint, it needs a map frame. So, I publish the map transformation somehow. Is it the same for you, or am I doing something wrong?

Additionally, if we plan to use this package only on the mapping side, I think it would be better to come up with a solution rather than compiling the entire Autoware. Do you have any plans to add just the lidar_centerpoint or any 3D object detection algorithm to the package? Combining a solution that takes only point cloud as an input, detects and removes objects in a single package would be more convenient. Additionally, it wouldn't require additional transformations on the Autoware side (map frame).

**Comment by davutcanakbas** [comment]
Hi, thank you for your cooperation.

You can adjust this line with your sensor frame, but it's important to note that this change is primarily needed when you're performing mapping tasks. ( autoware.universe/perception/lidar_centerpoint/launch/lidar_centerpoint.launch.xml )

`    <param name="densification_world_frame_id" value="Sensor_Frame_x"/>
`

I brought this up during the meeting, and the consensus was to keep it as is, with separate repositories and usage structured in this manner.

**Comment by StepTurtle** [comment]
Thanks for your answer.

> You can adjust this line with your sensor frame, but it's important to note that this change is primarily needed when you're performing mapping tasks. ( autoware.universe/perception/lidar_centerpoint/launch/lidar_centerpoint.launch.xml )

problem solved after doing this. Also adding this info to README will be useful for users.

> I brought this up during the meeting, and the consensus was to keep it as is, with separate repositories and usage structured in this manner.

I remember that it was decided in the meeting to create a separate repository for the package anddo not  add it to autoware.universe. Additionally, it is find more convenient to include lidar_centerpoint and its dependencies in this repository and use them.

**Comment by davutcanakbas** [comment]
I agree with this let's talk about it in the meeting. We can close the issue if everything is okay.
> Additionally, it is find more convenient to include lidar_centerpoint and its dependencies in this repository and use them.

**Comment by StepTurtle** [comment]
I updated the document as requested at the meeting. If there is nothing else left, we can close this issue.
Doc. link: https://gist.github.com/StepTurtle/4e74492489073c053883888be57bb1e4
